{"name": "test_answer", "status": "failed", "statusDetails": {"message": "AssertionError: assert 4 == 5", "trace": "def test_answer():\n>       assert func(3) == 5\nE       assert 4 == 5\n\ntest_demo.py:12: AssertionError"}, "start": 1612242290259, "stop": 1612242290259, "uuid": "b36e67e6-b71f-4764-bd2e-aa0468eadc5b", "historyId": "8eb971d13b0d6a43fe517151dead2e2a", "testCaseId": "f09542d7d0cd3629beb2fa5024c22587", "fullName": "test_demo#test_answer", "labels": [{"name": "suite", "value": "test_demo"}, {"name": "host", "value": "wangwei"}, {"name": "thread", "value": "1056-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_demo"}]}