{"name": "test_01", "status": "failed", "statusDetails": {"message": "pytest_assume.plugin.FailedAssumption: \n2 Failed Assumptions:\n\ntest_assume_8_2.py:31: AssumptionFailure\n>>\tpytest.assume(0 == 1)\nAssertionError: assert False\n\ntest_assume_8_2.py:33: AssumptionFailure\n>>\tpytest.assume(1 == 2)\nAssertionError: assert False", "trace": "tp = <class 'pytest_assume.plugin.FailedAssumption'>, value = None, tb = None\n\n    def reraise(tp, value, tb=None):\n        try:\n            if value is None:\n                value = tp()\n            if value.__traceback__ is not tb:\n>               raise value.with_traceback(tb)\nE               pytest_assume.plugin.FailedAssumption: \nE               2 Failed Assumptions:\nE               \nE               test_assume_8_2.py:31: AssumptionFailure\nE               >>\tpytest.assume(0 == 1)\nE               AssertionError: assert False\nE               \nE               test_assume_8_2.py:33: AssumptionFailure\nE               >>\tpytest.assume(1 == 2)\nE               AssertionError: assert False\n\n../../xunivenvs/hogwarts/lib/python3.6/site-packages/six.py:702: FailedAssumption"}, "description": "用例1", "start": 1622772836524, "stop": 1622772836521, "uuid": "e2ab36c7-e8e2-4efd-8bef-6b0053ae78e0", "historyId": "b48499382163cdb39a0cf98b64a86173", "testCaseId": "92692fabc119ee82a2a0f8edd8f52964", "fullName": "test_assume_8_2.Test#test_01", "labels": [{"name": "suite", "value": "test_assume_8_2"}, {"name": "subSuite", "value": "Test"}, {"name": "host", "value": "warronMacBook-Pro.local"}, {"name": "thread", "value": "54587-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_assume_8_2"}]}