{"name": "test_a", "status": "skipped", "statusDetails": {"message": "XFAIL deliberate fail\n\nAssertionError: assert False", "trace": "@pytest.mark.dependency()\n    @pytest.mark.xfail(reason=\"deliberate fail\")\n    def test_a(): #失败的case\n>       assert False\nE       assert False\n\ntest_dependency.py:16: AssertionError"}, "start": 1612423398978, "stop": 1612423398978, "uuid": "598b1edd-12ec-4f6e-9503-f6cc3fa70075", "historyId": "10618701e461573bbe81d2066362ad28", "testCaseId": "cb23bc25d0dd17b603b8d99a5b287bd8", "fullName": "test_dependency#test_a", "labels": [{"name": "tag", "value": "dependency"}, {"name": "tag", "value": "@pytest.mark.xfail(reason='deliberate fail')"}, {"name": "suite", "value": "test_dependency"}, {"name": "host", "value": "wangwei"}, {"name": "thread", "value": "3216-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_dependency"}]}